// <auto-generated />
using Dzienik_szkolny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dzienik_szkolny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719102507_PoprawionoStruktureTabeli")]
    partial class PoprawionoStruktureTabeli
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dzienik_szkolny.Models.AdresUzytkownika", b =>
                {
                    b.Property<long>("IdAdresu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdAdresu"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("IdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NrMieszkania")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdAdresu");

                    b.ToTable("AdresUzytkownika");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjePracownik", b =>
                {
                    b.Property<long>("IdPracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdPracownika"));

                    b.Property<long>("IdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("LoginIdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("IdPracownika");

                    b.HasIndex("LoginIdUzytkownika");

                    b.ToTable("InformacjePracownik");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjeRodzic", b =>
                {
                    b.Property<long>("IdRodzica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdRodzica"));

                    b.Property<long>("AdresIdAdresu")
                        .HasColumnType("bigint");

                    b.Property<long>("IdAdresu")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("LoginIdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("IdRodzica");

                    b.HasIndex("AdresIdAdresu");

                    b.HasIndex("LoginIdUzytkownika");

                    b.ToTable("InformacjeUzytkownik");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.ListaRole", b =>
                {
                    b.Property<long>("IdRoli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdRoli"));

                    b.Property<string>("NazwaRoli")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdRoli");

                    b.ToTable("ListaRole");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.LoczenieRoli", b =>
                {
                    b.Property<long>("IdLoczenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdLoczenia"));

                    b.Property<long>("IdRoli")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginIdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<long>("RolaIdRoli")
                        .HasColumnType("bigint");

                    b.HasKey("IdLoczenia");

                    b.HasIndex("LoginIdUzytkownika");

                    b.HasIndex("RolaIdRoli");

                    b.ToTable("LoczenieRoli");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.LoginUzytkownika", b =>
                {
                    b.Property<long>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdUzytkownika"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZaszyfrowaneHaslo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdUzytkownika");

                    b.ToTable("LoginyUzytkowiow");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjePracownik", b =>
                {
                    b.HasOne("Dzienik_szkolny.Models.LoginUzytkownika", "Login")
                        .WithMany()
                        .HasForeignKey("LoginIdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjeRodzic", b =>
                {
                    b.HasOne("Dzienik_szkolny.Models.AdresUzytkownika", "Adres")
                        .WithMany("Uzytkownikcy")
                        .HasForeignKey("AdresIdAdresu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dzienik_szkolny.Models.LoginUzytkownika", "Login")
                        .WithMany()
                        .HasForeignKey("LoginIdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.LoczenieRoli", b =>
                {
                    b.HasOne("Dzienik_szkolny.Models.LoginUzytkownika", "Login")
                        .WithMany()
                        .HasForeignKey("LoginIdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dzienik_szkolny.Models.ListaRole", "Rola")
                        .WithMany()
                        .HasForeignKey("RolaIdRoli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.AdresUzytkownika", b =>
                {
                    b.Navigation("Uzytkownikcy");
                });
#pragma warning restore 612, 618
        }
    }
}
