// <auto-generated />
using Dzienik_szkolny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dzienik_szkolny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718105644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dzienik_szkolny.Models.AdresUzytkownika", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("IdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NrMieszkania")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.ToTable("AdresUzytkownika");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjeUzytkownik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdresUzytkownikaid")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("LoginIdUzytkownika")
                        .HasColumnType("bigint");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("AdresUzytkownikaid");

                    b.HasIndex("LoginIdUzytkownika");

                    b.ToTable("InformacjeUzytkownik");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.LoginyUzytkownikow", b =>
                {
                    b.Property<long>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdUzytkownika"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZaszyfrowaneHaslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUzytkownika");

                    b.ToTable("LoginyUzytkowiow");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.InformacjeUzytkownik", b =>
                {
                    b.HasOne("Dzienik_szkolny.Models.AdresUzytkownika", null)
                        .WithMany("Uzytkownikcy")
                        .HasForeignKey("AdresUzytkownikaid");

                    b.HasOne("Dzienik_szkolny.Models.LoginyUzytkownikow", "Login")
                        .WithMany()
                        .HasForeignKey("LoginIdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("Dzienik_szkolny.Models.AdresUzytkownika", b =>
                {
                    b.Navigation("Uzytkownikcy");
                });
#pragma warning restore 612, 618
        }
    }
}
